"""add_module_permissions_system

Revision ID: 1cf67a6ef659
Revises: f9245e312a60
Create Date: 2025-09-16 13:59:21.475347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf67a6ef659'
down_revision: Union[str, None] = 'f9245e312a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('route_pattern', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=True)
    op.create_table('module_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_module_id', sa.Integer(), nullable=False),
    sa.Column('dependent_module_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dependent_module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['parent_module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_module_id', 'dependent_module_id')
    )
    op.create_index(op.f('ix_module_dependencies_id'), 'module_dependencies', ['id'], unique=False)
    op.create_table('user_module_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('granted_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id')
    )
    op.create_index(op.f('ix_user_module_permissions_id'), 'user_module_permissions', ['id'], unique=False)
    
    # Seed modules data
    op.execute("""
        INSERT INTO modules (name, display_name, route_pattern, description, is_core) VALUES
        -- Core modules (always accessible)
        ('dashboard', 'Dashboard', '/', 'Główny panel użytkownika', true),
        ('konta_allegro', 'Konta Allegro', '/accounts', 'Zarządzanie kontami Allegro', true),
        ('profil', 'Profil', '/profile', 'Profil użytkownika i ustawienia', true),
        
        -- Restricted modules
        ('edytor_ofert', 'Edytor Ofert', '/offer-editor', 'Masowa aktualizacja opisów z AI', false),
        ('kopiowanie_ofert', 'Kopiowanie Ofert', '/copy-offers', 'Kopiuj oferty między kontami', false),
        ('promocje', 'Promocje', '/promotions', 'Zarządzaj promocjami i rabatami', false),
        ('tytuly', 'Tytuły', '/titles', 'Pobieraj, edytuj i przywracaj tytuły ofert', false),
        ('miniatury', 'Miniatury', '/thumbnails', 'Zarządzaj miniaturkami ofert', false),
        ('podmiana_zdjec', 'Podmiana Zdjęć', '/replace-images', 'Nakładaj kompozytowe obrazy na zdjęcia', false),
        ('wylaczanie_ofert', 'Wyłączanie Ofert', '/disable-offers', 'Masowo zakańczaj lub przywracaj oferty', false),
        ('zdjecia_na_banerach', 'Zdjęcia na Banerach', '/banner-images', 'Zarządzaj zdjęciami banerów', false),
        ('karty_produktowe', 'Karty Produktowe', '/product-cards', 'Generuj karty produktowe PDF', false),
        
        -- Dependency modules (auto-granted based on other permissions)
        ('dodawanie_grafik', 'Dodawanie Grafik', '/images', 'Dodawaj i zarządzaj grafikami', false),
        ('zapisane_zdjecia', 'Zapisane Zdjęcia', '/saved-images', 'Zarządzaj zapisanymi obrazami', false),
        ('zuzycie_ai', 'Zużycie AI', '/usage', 'Monitoruj zużycie AI', false)
    """)
    
    # Set up module dependencies
    op.execute("""
        INSERT INTO module_dependencies (parent_module_id, dependent_module_id)
        SELECT 
            p.id as parent_module_id,
            d.id as dependent_module_id
        FROM modules p, modules d
        WHERE 
            (p.name = 'edytor_ofert' AND d.name IN ('dodawanie_grafik', 'zapisane_zdjecia', 'zuzycie_ai'))
            OR
            (p.name = 'karty_produktowe' AND d.name = 'dodawanie_grafik')
    """)
    
    # Grant all restricted modules to existing users (maintain current functionality)
    op.execute("""
        INSERT INTO user_module_permissions (user_id, module_id, granted, granted_by_admin_id)
        SELECT 
            u.id as user_id,
            m.id as module_id,
            true as granted,
            1 as granted_by_admin_id
        FROM users u 
        CROSS JOIN modules m 
        WHERE m.is_core = false
        AND u.id IS NOT NULL
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_module_permissions_id'), table_name='user_module_permissions')
    op.drop_table('user_module_permissions')
    op.drop_index(op.f('ix_module_dependencies_id'), table_name='module_dependencies')
    op.drop_table('module_dependencies')
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
