"""remove_unique_constraint_from_account_name

Revision ID: 76a71b6596e4
Revises: bcdc4c3ce7af
Create Date: 2025-07-04 21:19:09.538856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a71b6596e4'
down_revision: Union[str, None] = 'bcdc4c3ce7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_nazwa_konta'), table_name='accounts')
    op.create_index(op.f('ix_accounts_nazwa_konta'), 'accounts', ['nazwa_konta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_nazwa_konta'), table_name='accounts')
    op.create_index(op.f('ix_accounts_nazwa_konta'), 'accounts', ['nazwa_konta'], unique=1)
    # ### end Alembic commands ###
